'PR: waiting for review':
  - '*'  
  - '.github/**/*'
  - '_layouts/**/*'
  - 'about/**/*'
  - 'community/**/*'
  - 'development/**/*'
  - 'images/**/*'
  - 'usage/**/*'
  - '.gitignore'
  
'PR: dependencies':
  - 'Gemfile'
  - 'Gemfile.lock'
