name: Auto Merge PR
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Auto Merge PR
      if: contains(${{ github.event.pull_request.base.ref }}, 'master')
      run: |
        echo ${{ secrets.GH_TOKEN }} >> auth.txt
        gh auth login --with-token < auth.txt
        rm auth.txt
        gh pr merge https://github.com/FreeTubeApp/FreeTube-Docs/pull/${{ github.event.pull_request.number }} --auto --squash
